/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.constractor.calculator;

/**
 *
 * @author M.ASKAR
 */
public class Calculator extends javax.swing.JFrame {
        double num1 , num2 ;
        char operator ;
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        btn_AC = new javax.swing.JButton();
        btn_Del = new javax.swing.JButton();
        btn_mod = new javax.swing.JButton();
        btn_div = new javax.swing.JButton();
        btn_equal = new javax.swing.JButton();
        btn_plus = new javax.swing.JButton();
        btn_multiple = new javax.swing.JButton();
        btn_mainus = new javax.swing.JButton();
        btn_seven = new javax.swing.JButton();
        btn_eight = new javax.swing.JButton();
        btn_nine = new javax.swing.JButton();
        btn_six = new javax.swing.JButton();
        btn_four = new javax.swing.JButton();
        btn_five = new javax.swing.JButton();
        btn_one = new javax.swing.JButton();
        btn_two = new javax.swing.JButton();
        btn_three = new javax.swing.JButton();
        btn_zero = new javax.swing.JButton();
        btn_dot = new javax.swing.JButton();
        edit_text = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("jLabel1");

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("calculator");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lbl2.setBackground(new java.awt.Color(0, 0, 0));
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_AC.setBackground(new java.awt.Color(0, 0, 0));
        btn_AC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_AC.setForeground(java.awt.Color.orange);
        btn_AC.setText("AC");
        btn_AC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ACActionPerformed(evt);
            }
        });

        btn_Del.setBackground(new java.awt.Color(0, 0, 0));
        btn_Del.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Del.setForeground(java.awt.Color.orange);
        btn_Del.setText("DEL");
        btn_Del.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DelActionPerformed(evt);
            }
        });

        btn_mod.setBackground(new java.awt.Color(0, 0, 0));
        btn_mod.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_mod.setForeground(java.awt.Color.orange);
        btn_mod.setText("%");
        btn_mod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorAction(evt);
            }
        });

        btn_div.setBackground(new java.awt.Color(0, 0, 0));
        btn_div.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_div.setForeground(java.awt.Color.orange);
        btn_div.setText("/");
        btn_div.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorAction(evt);
            }
        });

        btn_equal.setBackground(new java.awt.Color(255, 153, 0));
        btn_equal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_equal.setForeground(new java.awt.Color(204, 204, 204));
        btn_equal.setText("=");
        btn_equal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_equalAction(evt);
            }
        });

        btn_plus.setBackground(new java.awt.Color(0, 0, 0));
        btn_plus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_plus.setForeground(java.awt.Color.orange);
        btn_plus.setText("+");
        btn_plus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorAction(evt);
            }
        });

        btn_multiple.setBackground(new java.awt.Color(0, 0, 0));
        btn_multiple.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_multiple.setForeground(java.awt.Color.orange);
        btn_multiple.setText("x");
        btn_multiple.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_multiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorAction(evt);
            }
        });

        btn_mainus.setBackground(new java.awt.Color(0, 0, 0));
        btn_mainus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_mainus.setForeground(java.awt.Color.orange);
        btn_mainus.setText("-");
        btn_mainus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_mainus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorAction(evt);
            }
        });

        btn_seven.setBackground(new java.awt.Color(0, 0, 0));
        btn_seven.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_seven.setForeground(new java.awt.Color(204, 204, 204));
        btn_seven.setText("7");
        btn_seven.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersAction(evt);
            }
        });

        btn_eight.setBackground(new java.awt.Color(0, 0, 0));
        btn_eight.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_eight.setForeground(new java.awt.Color(204, 204, 204));
        btn_eight.setText("8");
        btn_eight.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersAction(evt);
            }
        });

        btn_nine.setBackground(new java.awt.Color(0, 0, 0));
        btn_nine.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_nine.setForeground(new java.awt.Color(204, 204, 204));
        btn_nine.setText("9");
        btn_nine.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersAction(evt);
            }
        });

        btn_six.setBackground(new java.awt.Color(0, 0, 0));
        btn_six.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_six.setForeground(new java.awt.Color(204, 204, 204));
        btn_six.setText("6");
        btn_six.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersAction(evt);
            }
        });

        btn_four.setBackground(new java.awt.Color(0, 0, 0));
        btn_four.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_four.setForeground(new java.awt.Color(204, 204, 204));
        btn_four.setText("4");
        btn_four.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersAction(evt);
            }
        });

        btn_five.setBackground(new java.awt.Color(0, 0, 0));
        btn_five.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_five.setForeground(new java.awt.Color(204, 204, 204));
        btn_five.setText("5");
        btn_five.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersAction(evt);
            }
        });

        btn_one.setBackground(new java.awt.Color(0, 0, 0));
        btn_one.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_one.setForeground(new java.awt.Color(204, 204, 204));
        btn_one.setText("1");
        btn_one.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersAction(evt);
            }
        });

        btn_two.setBackground(new java.awt.Color(0, 0, 0));
        btn_two.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_two.setForeground(new java.awt.Color(204, 204, 204));
        btn_two.setText("2");
        btn_two.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersAction(evt);
            }
        });

        btn_three.setBackground(new java.awt.Color(0, 0, 0));
        btn_three.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_three.setForeground(new java.awt.Color(204, 204, 204));
        btn_three.setText("3");
        btn_three.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersAction(evt);
            }
        });

        btn_zero.setBackground(new java.awt.Color(0, 0, 0));
        btn_zero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_zero.setForeground(new java.awt.Color(204, 204, 204));
        btn_zero.setText("0");
        btn_zero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersAction(evt);
            }
        });

        btn_dot.setBackground(new java.awt.Color(0, 0, 0));
        btn_dot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_dot.setForeground(new java.awt.Color(204, 204, 204));
        btn_dot.setText(".");
        btn_dot.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dotActionPerformed(evt);
            }
        });

        edit_text.setBackground(new java.awt.Color(0, 0, 0));
        edit_text.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edit_text.setForeground(new java.awt.Color(255, 255, 255));
        edit_text.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edit_text.setText(" ");
        edit_text.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        edit_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_textActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_AC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Del, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_one, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_two, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_three, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_seven, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_eight, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_nine, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_four, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_five, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_six, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_multiple, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_mainus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_equal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))))
            .addComponent(edit_text)
            .addComponent(lbl2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(edit_text, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Del, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_seven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_multiple, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_nine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_six, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_four, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_five, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mainus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_one, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_two, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_three, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void operatorAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorAction
            // TODO add your handling code here:
           if (edit_text.getText().length() >0){
            switch(evt.getActionCommand()){
                case "+" :{
                    num1=Double.parseDouble(edit_text.getText());
                    operator= '+';
                    lbl2.setText(num1+"+");
                    edit_text.setText("");
                    break ;
                }
                case "-" :{
                    num1=Double.parseDouble(edit_text.getText());
                    operator= '-';
                    lbl2.setText(num1+"-");
                    edit_text.setText("");
                    break ;
                }
                case "x" :
                case "*" :{
                    num1=Double.parseDouble(edit_text.getText());
                    operator= 'x';
                    lbl2.setText(num1+"*");
                    edit_text.setText("");
                    break ;
                }
                case "/" :{
                    num1=Double.parseDouble(edit_text.getText());
                    operator= '/';
                    lbl2.setText(num1+"/");
                    edit_text.setText("");
                    break ;
                }
                case "%" :{
                    num1=Double.parseDouble(edit_text.getText());
                    operator= '%';
                    lbl2.setText(num1+"%");
                    edit_text.setText("");
                    break ;
                }
            }
            
           }
    }//GEN-LAST:event_operatorAction

    private void edit_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_textActionPerformed

    private void numbersAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbersAction

        // TODO add your handling code here:
        switch (evt.getActionCommand()){
            case "0":{
                if (edit_text.getText().length() > 0){
                
                    edit_text.setText(edit_text.getText()+"0");
                }
                break ;
            }
            case "1" :{
                edit_text.setText(edit_text.getText()+"1");
                break ;
            }
            case "2":{
                edit_text.setText(edit_text.getText()+"2");
                break ;
            }
            case "3" :{
                edit_text.setText(edit_text.getText()+"3");
                break ;
            }
            case "4":{
                edit_text.setText(edit_text.getText()+"4");
                break ;
            }
            case "5":{
                edit_text.setText(edit_text.getText()+"5");
                break ;
            }
            case "6":{
                edit_text.setText(edit_text.getText()+"6");
                break ;
            }
            case "7":{
                edit_text.setText(edit_text.getText()+"7");
                break;
            }
            case "8":{
                edit_text.setText(edit_text.getText()+"8");
                break ;
                
            }
            case "9":{
                edit_text.setText(edit_text.getText()+"9");
                break ;
            }
        }
    }//GEN-LAST:event_numbersAction

    private void btn_equalAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_equalAction
        // TODO add your handling code here:
        if (edit_text.getText().length()>0){
            num2=Double.parseDouble(edit_text.getText());
        } else {
            num2= num1 ;
            
        }
        
         double result=0 ;
         if (operator !='\u0000'){
         switch (operator){
             case '+' :{
                 result =num1 + num2 ;
                 
                 break ;
             }
             case '-' :{
                 result =num1 - num2 ;
                 break ;
             }
              case 'x' :{
                 result =num1 * num2 ;
               
                 break ;
             }
              case '/' :{
                 result =num1 / num2 ;
                 
                 break ;
             }
              case '%' :{
                 result =num1 % num2 ;
                 
                 break ;
             }
         }
         operator ='\u0000' ;
         edit_text.setText(""+result);
         lbl2.setText(lbl2.getText()+num2+"=");
               
       } else {
             edit_text.setText(num2+"");
         }
    }//GEN-LAST:event_btn_equalAction

    private void btn_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dotActionPerformed
        // TODO add your handling code here:
        if (!edit_text.getText().contains(".")){
            edit_text.setText(edit_text.getText()+".");
        }
    }//GEN-LAST:event_btn_dotActionPerformed

    private void btn_DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DelActionPerformed
        // TODO add your handling code here:
        if (edit_text.getText().length()>0){
        String number = edit_text.getText().substring(0, edit_text.getText().length()-1);
        edit_text.setText(number);
        }
        
    }//GEN-LAST:event_btn_DelActionPerformed

    private void btn_ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ACActionPerformed
        // TODO add your handling code here:
        edit_text.setText("");
        lbl2.setText("");
        
    }//GEN-LAST:event_btn_ACActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AC;
    private javax.swing.JButton btn_Del;
    private javax.swing.JButton btn_div;
    private javax.swing.JButton btn_dot;
    private javax.swing.JButton btn_eight;
    private javax.swing.JButton btn_equal;
    private javax.swing.JButton btn_five;
    private javax.swing.JButton btn_four;
    private javax.swing.JButton btn_mainus;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton btn_multiple;
    private javax.swing.JButton btn_nine;
    private javax.swing.JButton btn_one;
    private javax.swing.JButton btn_plus;
    private javax.swing.JButton btn_seven;
    private javax.swing.JButton btn_six;
    private javax.swing.JButton btn_three;
    private javax.swing.JButton btn_two;
    private javax.swing.JButton btn_zero;
    private javax.swing.JTextField edit_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl2;
    // End of variables declaration//GEN-END:variables
}
